version: '3.1'

services:
    pgvectordb:
        image: pgvector/pgvector:pg16
        restart: always
        container_name: pgvectordb
        ports:
        - "5432:5432"
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        networks:
          ai_network:
            ipv4_address: 172.25.0.2
        volumes:
        - pgvectordb_data:/var/lib/postgresql/data

    nginx-proxy:
        image: nginx:stable-alpine
        restart: always
        container_name: nginx-proxy
        ports:
        - "80:80"
        networks:
          ai_network:
            ipv4_address: 172.25.0.3
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - flowise

    flowise:
        image: hclareth7/flowise-agentez:latest
        restart: always
        container_name: flowise-agentez
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
            - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        networks:
          ai_network:
            ipv4_address: 172.25.0.10
        depends_on:
            - pgvectordb

networks:
  ai_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  pgvectordb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/postgresql/pgvectordb_data'
